//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YarielPrueba.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Persona
    {
        public int ID { get; set; }
        [DisplayName("*Nombre")]
        [Required(ErrorMessage ="Este campo es requerido")]      
        public string Nombre { get; set; }
        [DisplayName("*Fecha de Nacimiento")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "Este campo es requerido")]
        public DateTime FechaDeNacimiento { get; set; }


    }
}
