//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YarielPrueba.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class services_detail
    {
        public int id { get; set; }
        public string name { get; set; }
        public int id_services { get; set; }
        public Nullable<int> ServicesId { get; set; }   
        public virtual services services { get; set; }
    }
}
